# Generated by Django 5.2.4 on 2025-08-04 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScanResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_posted", models.DateTimeField()),
                ("source", models.TextField()),
                ("details", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("scan_start_date", models.DateTimeField(auto_now_add=True)),
                ("scan_end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("keywords", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScanSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("schedule_time", models.DateTimeField()),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("keywords", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "scanresult_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.scanresult",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("auteur", models.CharField(max_length=100)),
            ],
            bases=("main.scanresult",),
        ),
        migrations.CreateModel(
            name="ReseauSocial",
            fields=[
                (
                    "scanresult_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.scanresult",
                    ),
                ),
                ("auteur", models.CharField(max_length=100)),
                ("nombre_commentaires", models.IntegerField()),
                ("nombre_partages", models.IntegerField()),
                ("nombre_likes", models.IntegerField()),
            ],
            bases=("main.scanresult",),
        ),
        migrations.AddField(
            model_name="scanresult",
            name="scan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="main.scan",
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scans",
                to="main.scanschedule",
            ),
        ),
        migrations.AddField(
            model_name="scanschedule",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scan_schedules",
                to="main.sites",
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="sites",
            field=models.ManyToManyField(related_name="scans", to="main.sites"),
        ),
    ]
