# Generated by Django 5.2.4 on 2025-08-04 19:55

from django.db import migrations

def create_default_sites(apps, schema_editor):
    Sites = apps.get_model('main', 'Sites')
    Sites.objects.create(name='Twitter', url='https://twitter.com')
    Sites.objects.create(name='News API', url='https://newsapi.org')

def delete_default_sites(apps, schema_editor):
    Sites = apps.get_model('main', 'Sites')
    Sites.objects.filter(name__in=['Twitter', 'News API']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_sites, delete_default_sites),
    ]
