# Generated by Django 5.2.4 on 2025-08-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_falsealert"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="resolved",
            field=models.BooleanField(default=False),
        ),
    ]
