# Generated by Django 5.2.4 on 2025-08-10 10:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_alert_result_report_reportrecipients"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="time_run",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scanschedule",
            name="last_scan",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="main.scan"
            ),
        ),
        migrations.AddField(
            model_name="scanschedule",
            name="next_scan_time",
            field=models.DateTimeField(null=True, verbose_name="Scan"),
        ),
    ]
