# Generated by Django 5.2.4 on 2025-08-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_scan_time_run_scanschedule_last_scan_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scanschedule",
            name="site",
        ),
        migrations.AddField(
            model_name="scanschedule",
            name="site",
            field=models.ManyToManyField(
                related_name="scan_schedules", to="main.sites"
            ),
        ),
    ]
