# Generated by Django 5.2.4 on 2025-08-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_remove_scanschedule_site_scanschedule_site"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scanschedule",
            old_name="site",
            new_name="sites",
        ),
    ]
