# Generated by Django 5.2.4 on 2025-09-07 08:47

from django.db import migrations

def delete_twitter_site(apps, schema_editor):
    Sites = apps.get_model('main', 'Sites')
    Sites.objects.filter(name='Twitter').delete()

def restore_twitter_site(apps, schema_editor):
    Sites = apps.get_model('main', 'Sites')
    Sites.objects.get_or_create(name='Twitter', url='https://twitter.com')

class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_rename_severities"),
    ]

    operations = [migrations.RunPython(delete_twitter_site, restore_twitter_site)]
