# Generated by Django 5.2.4 on 2025-09-08 15:43

from django.db import migrations
from django.db.models import Q

def create_default_sites(apps, schema_editor):
    Alert = apps.get_model("main", "Alert")
    alerts_to_delete = Alert.objects.filter(~Q(severity__in=["low", "medium", "high"]))
    print(f"Deleting {alerts_to_delete.count()} alerts with 'none' severity...")
    alerts_to_delete.delete()

class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_delete_twitter_from_sites"),
    ]

    operations = [
        migrations.RunPython(create_default_sites),
    ]